# Generated by Django 4.2.4 on 2023-08-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapi', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('floor_number', models.IntegerField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
